name = "TestPackage"

# Development environment (folders added to the path when project is loaded)
[folders]
path = [
    "scripts",
    "resources",
]
test = [
    "tests",
]

[dependencies]
matlab_toml = {version = ">=1.3", id = "b07fcaf1-c632-4418-b3ff-199244221efc"}

[project]
summary = "Test of new TOML project structure"
startup-files = [
    "scripts/startup.m",
]
shutdown-files = [
    "scripts/shutdown.m",
]

[project.labels.test]

[[package]]
configuration-name = "Release"

name = "TestPackage"
display-name = "Test Package"
version = "0.3.0"

# Should match UUID assigned by File Exchange
id = "88a98551-056e-41b9-ac04-3f9a08225bf9"

# Execution environment (folders added to end-user path)
package-root = "/"
folders.path = ["."]

use-license-bsd = true
provider.name = "Martin"
provider.email = "martin.herreriasazcue@manchester.ac.uk"
provider.organization = "University of Manchester"
summary = "Test of new TOML package structure"
description = "An experiment for CI/CD of MATLAB toolboxes (soon 'packages'), trying to embrace the R2026b transition to TOML-based projects."

getting-started-file = "doc/GettingStarted.m"
preview-image-file = "resources/chicken-icon.png"

# R2025a is the first release to support toolbox.ignore
release-compatibility = "25.1.* - 26.2.*"
supported-platforms = [
    "windows",
    "linux",
    "macos",
]
