name = "TemplatePackage"

# Development environment (folders added to the path when project is loaded)
[folders]
path = [
    "scripts",
    ".",
]
test = [
    "tests",
]

[dependencies]
PkgBuild = {version = ">=1.0", id = "794f3978-8e02-4c93-9f6a-d5f4236db196"}

[project]
summary = "Template for TOML-based MATLAB package"
startup-files = [
    "scripts/startup.m",
]
shutdown-files = [
    "scripts/shutdown.m",
]

[[package]]
configuration-name = "Release"

name = "TemplatePackage"
display-name = "Template Package"
version = "0.0.0"

# Should match UUID assigned by File Exchange
# Use PkgBuild.newUUID for a new package
id = "abcd1234-5678-90ab-cdef-1234567890ab"

# Execution environment (folders added to end-user path)
package-root = "/"
folders.path = ["."]

use-license-bsd = true
provider.name = "John Doe"
provider.email = "john.doe@example.com"
provider.organization = "Example Organization"
summary = "Template for TOML-based MATLAB package"
description = "You should edit this description to describe your package"

getting-started-file = "doc/GettingStarted.m"
preview-image-file = "resources/chicken-icon.png"

# R2025a is the first release to support toolbox.ignore
release-compatibility = "25.1.* - 26.2.*"
supported-platforms = [
    "windows",
    "linux",
    "macos",
]
